services:
  ai_server_1:
    build: ./server
    expose:
      - "50051"
    env_file:
      - .env
      
  ai_server_2:
    build: ./server
    expose:
      - "50051"
    env_file:
      - .env

  ai_server_3:
    build: ./server
    expose:
      - "50051"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - ai_server_1
      - ai_server_2
      - ai_server_3