# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIInferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSentiment = channel.unary_unary(
                '/ai_inference.AIInference/AnalyzeSentiment',
                request_serializer=inference__pb2.SentimentRequest.SerializeToString,
                response_deserializer=inference__pb2.SentimentResponse.FromString,
                _registered_method=True)
        self.StreamChat = channel.unary_stream(
                '/ai_inference.AIInference/StreamChat',
                request_serializer=inference__pb2.PromptRequest.SerializeToString,
                response_deserializer=inference__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.SummarizeDocument = channel.stream_unary(
                '/ai_inference.AIInference/SummarizeDocument',
                request_serializer=inference__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=inference__pb2.UploadFileResponse.FromString,
                _registered_method=True)
        self.LiveAssistant = channel.stream_stream(
                '/ai_inference.AIInference/LiveAssistant',
                request_serializer=inference__pb2.ChatMessage.SerializeToString,
                response_deserializer=inference__pb2.ChatMessage.FromString,
                _registered_method=True)


class AIInferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeSentiment(self, request, context):
        """Unary (Sentiment)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChat(self, request, context):
        """Server streaming (Chat generation)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeDocument(self, request_iterator, context):
        """Client streaming (Summarization)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiveAssistant(self, request_iterator, context):
        """Bidirectional (Live assistant)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSentiment,
                    request_deserializer=inference__pb2.SentimentRequest.FromString,
                    response_serializer=inference__pb2.SentimentResponse.SerializeToString,
            ),
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=inference__pb2.PromptRequest.FromString,
                    response_serializer=inference__pb2.TokenResponse.SerializeToString,
            ),
            'SummarizeDocument': grpc.stream_unary_rpc_method_handler(
                    servicer.SummarizeDocument,
                    request_deserializer=inference__pb2.UploadFileRequest.FromString,
                    response_serializer=inference__pb2.UploadFileResponse.SerializeToString,
            ),
            'LiveAssistant': grpc.stream_stream_rpc_method_handler(
                    servicer.LiveAssistant,
                    request_deserializer=inference__pb2.ChatMessage.FromString,
                    response_serializer=inference__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_inference.AIInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_inference.AIInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIInference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.AIInference/AnalyzeSentiment',
            inference__pb2.SentimentRequest.SerializeToString,
            inference__pb2.SentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_inference.AIInference/StreamChat',
            inference__pb2.PromptRequest.SerializeToString,
            inference__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeDocument(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ai_inference.AIInference/SummarizeDocument',
            inference__pb2.UploadFileRequest.SerializeToString,
            inference__pb2.UploadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiveAssistant(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ai_inference.AIInference/LiveAssistant',
            inference__pb2.ChatMessage.SerializeToString,
            inference__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
