# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x0c\x61i_inference\" \n\x10SentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"6\n\x11SentimentResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"\x1f\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1e\n\rTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\x1d\n\rDocumentChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x0fSummaryResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t2\xca\x02\n\x0b\x41IInference\x12S\n\x10\x41nalyzeSentiment\x12\x1e.ai_inference.SentimentRequest\x1a\x1f.ai_inference.SentimentResponse\x12H\n\nStreamChat\x12\x1b.ai_inference.PromptRequest\x1a\x1b.ai_inference.TokenResponse0\x01\x12Q\n\x11SummarizeDocument\x12\x1b.ai_inference.DocumentChunk\x1a\x1d.ai_inference.SummaryResponse(\x01\x12I\n\rLiveAssistant\x12\x19.ai_inference.ChatMessage\x1a\x19.ai_inference.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENTIMENTREQUEST']._serialized_start=33
  _globals['_SENTIMENTREQUEST']._serialized_end=65
  _globals['_SENTIMENTRESPONSE']._serialized_start=67
  _globals['_SENTIMENTRESPONSE']._serialized_end=121
  _globals['_PROMPTREQUEST']._serialized_start=123
  _globals['_PROMPTREQUEST']._serialized_end=154
  _globals['_TOKENRESPONSE']._serialized_start=156
  _globals['_TOKENRESPONSE']._serialized_end=186
  _globals['_DOCUMENTCHUNK']._serialized_start=188
  _globals['_DOCUMENTCHUNK']._serialized_end=217
  _globals['_SUMMARYRESPONSE']._serialized_start=219
  _globals['_SUMMARYRESPONSE']._serialized_end=253
  _globals['_CHATMESSAGE']._serialized_start=255
  _globals['_CHATMESSAGE']._serialized_end=299
  _globals['_AIINFERENCE']._serialized_start=302
  _globals['_AIINFERENCE']._serialized_end=632
# @@protoc_insertion_point(module_scope)
