events {}
http {
    upstream ai_backend {
        server ai_server_1:50051;
        server ai_server_2:50051;
        server ai_server_3:50051;
    }

    server {
        listen 80;
        http2 on; # Required for gRPC
        
        location / {
            grpc_pass grpc://ai_backend;
        }
    }
}